# Site settings
title: Data Science is not a thing
email: antoniotropiano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog that collects all things I try (and fail) on my way to...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tropiano.github.io" # the base hostname & protocol for your site
twitter_username: tropianhs
github_username:  tropiano

# Build settings
markdown: kramdown
